### ISSUE TITLE
Include Datomic-Free License

### ISSUE THREAD

**Issue by jjtolton** [gws/docker-datomic-free-transactor#1]
Thanks so much for your work!  Don't forget to include the Datomic Free license, which simply states that software using Datomic Free needs to display the license :)

**Comment by jjtolton** [comment]
https://www.datomic.com/datomic-free-edition-license.html

**Comment by gws** [comment]
@jjtolton Thank you! I've resolved this in https://github.com/gws/docker-datomic-free-transactor/commit/6fede45ec9f472d3a0d7a0b8448e9deb84ef4ca1
